"use strict";

const MAP_SETTINGS = Object.freeze({
  dimensions: [6130, 6180],
  initialZoom: 3,
  maxZoom: 7,
  minZoom: 1,
  tilePath: './tiles/{z}/{x}/{y}.png',
  attribution: 'Created by <a href="https://github.com/Joshua2504" target="_blank">Joshua2504</a><br>Contribute on <a href="https://github.com/CoR-Forum/Regnum.Online" target="_blank">GitHub</a><br>...'
});

const map = L.map('map', {
  crs: L.CRS.Simple,
  minZoom: MAP_SETTINGS.minZoom,
  maxZoom: MAP_SETTINGS.maxZoom
});

const rasterCoords = new L.RasterCoords(map, MAP_SETTINGS.dimensions);
map.setMaxZoom(rasterCoords.zoomLevel(MAP_SETTINGS.maxZoom));
map.setView(rasterCoords.unproject([
  MAP_SETTINGS.dimensions[0] / 2,
  MAP_SETTINGS.dimensions[1] / 2
]), MAP_SETTINGS.initialZoom);

L.tileLayer(MAP_SETTINGS.tilePath, {
  attribution: MAP_SETTINGS.attribution,
  noWrap: true
}).addTo(map);

const toLatLng = coords => rasterCoords.unproject(coords);

const icons = Object.freeze({
  npc: L.icon.mapkey({ icon: 'n', color: 'white', background: 'blue', size: 5 }),
  city: L.icon.mapkey({ icon: 'cityhall', size: 25 }),
  castle: L.icon.mapkey({ icon: 'castle', size: 25 }),
  fort: L.icon.mapkey({ icon: 'fort', size: 25 }),
  sight: L.icon.mapkey({ icon: 'eye', color: 'blue', background: 'yellow', size: 15 }),
  craftingNpc: L.icon.mapkey({ icon: 'n', color: 'white', background: 'red', size: 5 }),
  craftingBoss: L.icon.mapkey({ icon: 'adit', color: 'white', background: 'red', size: 25 }),
  craftingBossSmall: L.icon.mapkey({ icon: 'adit', color: 'white', background: 'red', size: 20 }),
  shop: L.icon.mapkey({ icon: 'market_place', color: 'white', background: '#a37ec7', size: 20 }),
  champion: L.icon.mapkey({ icon: 'battlefield', color: 'white', background: '#a37ec7', size: 20 }),
  teleporter: L.icon.mapkey({ icon: 'airport', color: 'white', background: 'blue', size: 20 }),
  superbossDaenRha: L.icon({ iconUrl: 'images/icons/daen_rha.png', iconSize: [30, 44] }),
  superbossEvendim: L.icon({ iconUrl: 'images/icons/evendim.png', iconSize: [26, 44] }),
  superbossThorkul: L.icon({ iconUrl: 'images/icons/thorkul.png', iconSize: [27, 32] }),
  sightIsland: L.icon({ iconUrl: 'images/icons/sight_island_1.png', iconSize: [25, 25] }),
  altar: L.icon({ iconUrl: 'images/icons/altar.png', iconSize: [16, 16] }),
  pendants: L.AwesomeMarkers.icon({ prefix: 'fa', icon: 'balance-scale', markerColor: 'red' })
});

const createMarker = ({ coords, icon, tooltip, popup, openTooltip }) => {
  const marker = L.marker(toLatLng(coords), { icon });
  if (tooltip) marker.bindTooltip(tooltip);
  if (popup) marker.bindPopup(popup);
  if (openTooltip) marker.openTooltip();
  return marker;
};

const buildLayerGroup = entries => L.layerGroup(entries.map(createMarker));

const overlayDefinitions = Object.freeze({
  'NPCs': [
    { id: 'arena_syrtis', coords: [2957, 5542], icon: icons.npc, tooltip: '<b>Arena Guardian</b>', openTooltip: true },
    { id: 'igna_myneely', coords: [4308.97, 6048.77], icon: icons.npc, tooltip: '<b>Igna McNeely</b> (Neutral Denizen)', openTooltip: true },
    { id: 'melarak', coords: [2395, 4672], icon: icons.npc, tooltip: '<b>Melarak</b> (Herbalist)', openTooltip: true },
    { id: 'dalmora', coords: [2936.81, 2887.72], icon: icons.npc, tooltip: '<b>Dalmora</b> (Neutral Denizen)', openTooltip: true },
    { id: 'eric_vantassle', coords: [312.12, 1859.17], icon: icons.npc, tooltip: '<b>Eric Vantassle</b> (Weaponsmith)', openTooltip: true },
    { id: 'vermil_shadowborn', coords: [318.69, 1851.97], icon: icons.npc, tooltip: '<b>Vermil Shadowborn</b> (Blacksmith)', openTooltip: true },
    { id: 'boltar', coords: [1732, 3061], icon: icons.npc, tooltip: '<b>Boltar</b> (Alsius Denizen)', openTooltip: true },
    { id: 'tenax_npc', coords: [4258, 1565], icon: icons.npc, tooltip: '<b>Guardian de la Cueva</b> (Guard)', openTooltip: true },
    { id: 'tarsus', coords: [1104.61, 456.02], icon: icons.npc, tooltip: '<b>Tarsus</b> (Denizen)', openTooltip: true },
    { id: 'asgeir', coords: [904.76, 1326.65], icon: icons.npc, tooltip: '<b>Asgeir</b> (Clan Notary)', openTooltip: true },
    { id: 'dardanus_shadowhawk', coords: [3494.86, 3476.51], icon: icons.npc, tooltip: '<b>Dardanus Shadowhawk</b> (Merchant)', openTooltip: true },
    { id: 'sighild', coords: [828.94, 1178.82], icon: icons.npc, tooltip: '<b>Sighild</b> (Denizen)', openTooltip: true },
    { id: 'alastor_npc', coords: [1678, 979], icon: icons.npc, tooltip: '<b>Guardian de la Cueva</b> (Guard)', openTooltip: true },
    { id: 'vesper_npc', coords: [2407, 5455], icon: icons.npc, tooltip: '<b>Guardian de la Cueva</b> (Guard)', openTooltip: true },
    { id: 'vilcor', coords: [754.72, 1908.03], icon: icons.npc, tooltip: '<b>Vilcor</b> (Denizen)', openTooltip: true },
    { id: 'vania_vantassle_shadowborn', coords: [533, 1920], icon: icons.npc, tooltip: '<b>Vania Vantassle Shadowborn</b> (Denizen)', openTooltip: true },
    { id: 'laranda_shadowhawk', coords: [2197, 5468], icon: icons.npc, tooltip: '<b>Laranda Shadowhawk</b> (Denizen)', openTooltip: true },
    { id: 'malaguy', coords: [2359.52, 5578.16], icon: icons.npc, tooltip: '<b>Malaguy</b> (Denizen)', openTooltip: true }
  ],
  'Champions': [
    { id: 'soras', coords: [1640, 5690], icon: icons.champion, tooltip: '<b>Soras (LV9)</b><br>Drop: Amulet', openTooltip: true },
    { id: 'punzas', coords: [1500, 5880], icon: icons.champion, tooltip: '<b>Punzas (LV10)</b><br>Drop: Bow', openTooltip: true },
    { id: 'avalon', coords: [1200, 4800], icon: icons.champion, tooltip: '<b>Avalon (LV19)</b><br>Drop: Amulet', openTooltip: true },
    { id: 'rizofag', coords: [1930, 4500], icon: icons.champion, tooltip: '<b>Rizofag (LV31)</b><br>Drop: Shield', openTooltip: true },
    { id: 'sambro', coords: [2050, 5300], icon: icons.champion, tooltip: '<b>Sambro</b><br>Drop: Staff', openTooltip: true },
    { id: 'satarco', coords: [2870, 4620], icon: icons.champion, tooltip: '<b>Satarco (LV50)</b><br>Drop: Sword', openTooltip: true },
    { id: 'yelamid', coords: [5400, 530], icon: icons.champion, tooltip: '<b>Yelamid (LV10)</b>', openTooltip: true },
    { id: 'gohos', coords: [4550, 1200], icon: icons.champion, tooltip: '<b>Gohos</b>', openTooltip: true },
    { id: 'jidenah', coords: [4300, 1600], icon: icons.champion, tooltip: '<b>Jidenah (LV28)</b>', openTooltip: true },
    { id: 'graj', coords: [5340, 2820], icon: icons.champion, tooltip: '<b>Graj (LV42)</b>', openTooltip: true },
    { id: 'kontaron', coords: [5400, 2625], icon: icons.champion, tooltip: '<b>Kontaron (LV50)</b>', openTooltip: true },
    { id: 'thorburn', coords: [620, 480], icon: icons.champion, tooltip: '<b>Thorburn (LV9)</b><br>Drop: Helm', openTooltip: true },
    { id: 'levias', coords: [179, 1045], icon: icons.champion, tooltip: '<b>Levias (LV11)</b><br>Drop: Amulet', openTooltip: true },
    { id: 'olumor', coords: [1560, 1080], icon: icons.champion, tooltip: '<b>Olumor</b><br>Drop: Tunika', openTooltip: true },
    { id: 'gorlak', coords: [1100, 1950], icon: icons.champion, tooltip: '<b>Gorlag (LV29)</b><br>Drop: Bow', openTooltip: true },
    { id: 'ades', coords: [2000, 1700], icon: icons.champion, tooltip: '<b>Ades (LV40)</b><br>Drop: Staff', openTooltip: true },
    { id: 'asyr', coords: [1685, 1530], icon: icons.champion, tooltip: '<b>Asyr (LV50)</b><br>Drop: Amulet', openTooltip: true },
    { id: 'daen_rha', coords: [3890, 2618], icon: icons.superbossDaenRha, tooltip: '<b>Daen Rha</b><br><img src="images/icons/daen_rha.png">', openTooltip: true },
    { id: 'evendim', coords: [3144, 3767], icon: icons.superbossEvendim, tooltip: '<b>Evendim</b><br><img src="images/icons/evendim.png">', openTooltip: true },
    { id: 'thorkul', coords: [2334, 1968], icon: icons.superbossThorkul, tooltip: '<b>Thorkul</b><br><img src="images/icons/thorkul.png">', openTooltip: true }
  ],
  'Superbosses': [
    { id: 'daen_rha', coords: [3890, 2618], icon: icons.superbossDaenRha, tooltip: '<b>Daen Rha</b><br><img src="images/icons/daen_rha.png">', openTooltip: true },
    { id: 'evendim', coords: [3144, 3767], icon: icons.superbossEvendim, tooltip: '<b>Evendim</b><br><img src="images/icons/evendim.png">', openTooltip: true },
    { id: 'thorkul', coords: [2334, 1968], icon: icons.superbossThorkul, tooltip: '<b>Thorkul</b><br><img src="images/icons/thorkul.png">', openTooltip: true }
  ],
  'Crafting': [
    { id: 'rodlut', coords: [2642, 1219], icon: icons.craftingNpc, tooltip: '<b>Rodlut</b> (Craftmaster)', openTooltip: true },
    { id: 'nekhbit', coords: [4175, 2458], icon: icons.craftingBoss, tooltip: '<b>Nekhbit (LV61)</b>', openTooltip: true },
    { id: 'mrotgor', coords: [2210, 3770], icon: icons.craftingBoss, tooltip: '<b>Mrotgor (LV61)</b>', openTooltip: true },
    { id: 'bjarr', coords: [2180, 1800], icon: icons.craftingBoss, tooltip: '<b>Bjarr (LV61)</b>', openTooltip: true },
    { id: 'urrgog', coords: [2767, 2249], icon: icons.craftingBossSmall, tooltip: '<b>Urrgog (LV60)</b>', openTooltip: true },
    { id: 'kregog', coords: [3910, 2916], icon: icons.craftingBossSmall, tooltip: '<b>Kregog (LV60)</b>', openTooltip: true },
    { id: 'kurgo', coords: [1976, 1992], icon: icons.craftingBossSmall, tooltip: '<b>Kurgo (LV30)</b>', openTooltip: true },
    { id: 'tokmo', coords: [3785, 1970], icon: icons.craftingBossSmall, tooltip: '<b>Tokmo (LV30)</b>', openTooltip: true },
    { id: 'delebon', coords: [2807, 4102], icon: icons.craftingBossSmall, tooltip: '<b>Delebon (LV30)</b>', openTooltip: true },
    { id: 'gobgog', coords: [1989, 3008], icon: icons.craftingBossSmall, tooltip: '<b>Gobgog (LV60)</b>', openTooltip: true },
    { id: 'tenax', coords: [4252, 1569], icon: icons.craftingBoss, tooltip: '<b>Tenax</b>', openTooltip: true },
    { id: 'alastor', coords: [1662, 979], icon: icons.craftingBoss, tooltip: '<b>Alastor</b>', openTooltip: true },
    { id: 'vesper', coords: [2375, 5464], icon: icons.craftingBoss, tooltip: '<b>Vesper</b>', openTooltip: true },
    { id: 'eadmar_bronzearm', coords: [2424.12, 4372.5], icon: icons.craftingNpc, tooltip: '<b>Eadmer Bronzearm</b> (Craftmaster)', openTooltip: true },
    { id: 'lorvel', coords: [1088.2, 4577.25], icon: icons.craftingNpc, tooltip: '<b>Lorvel</b> (Craftmaster)', openTooltip: true },
    { id: 'lulia', coords: [1169.92, 2075.06], icon: icons.craftingNpc, tooltip: '<b>Lulia</b> (Craftmaster)', openTooltip: true },
    { id: 'osthan', coords: [950.11, 1323.02], icon: icons.craftingNpc, tooltip: '<b>Osthan</b> (Craftmaster)', openTooltip: true },
    { id: 'tuldor', coords: [156.02, 2049.79], icon: icons.craftingNpc, tooltip: '<b>Tuldor</b> (Craftmaster)', openTooltip: true }
  ],
  'Shops': [
    { id: 'shop_imperia', coords: [2876, 1808], icon: icons.shop, popup: '<b>Korbus</b> (Alsius Weaponsmith)' },
    { id: 'shop_samal', coords: [3694, 2247], icon: icons.shop },
    { id: 'shop_herbred', coords: [2595, 3464], icon: icons.shop },
    { id: 'shop_aggers', coords: [2378, 2326], icon: icons.shop, popup: '<b>Tria, Rotaren (Merchant), Makret</b>' },
    { id: 'shop_shaanarid', coords: [4085, 3128], icon: icons.shop, popup: '<b>Sigfrid (Weaponsmith)</b>' },
    { id: 'shop_menirah', coords: [3500, 1440], icon: icons.shop, popup: '<b>Sultar (Zauberer), Imrak (Zauberer), Rodlah (Merchant), Akite (Bogner)</b>' },
    { id: 'shop_algaros', coords: [1455, 3265], icon: icons.shop, popup: '<b>Arabell (Weaponsmith), Aren Miret (Weaponsmith), Mia Arle (Zauberer), Deina (Merchant)</b>' },
    { id: 'shop_eferias', coords: [3513, 4156], icon: icons.shop, popup: '<b>Jabeline (Bogner)</b>' }
  ],
  'Cities': [
    { id: 'fisgael', coords: [1121.22, 4580.7], icon: icons.city, tooltip: '<b>Fisgael City</b>', openTooltip: true },
    { id: 'korsum', coords: [1648, 3901], icon: icons.city, tooltip: '<b>Korsum</b>', openTooltip: true },
    { id: 'raeraia', coords: [2388, 4405], icon: icons.city, tooltip: '<b>Raeraia</b>', openTooltip: true },
    { id: 'dohsim', coords: [2758, 5206], icon: icons.city, tooltip: '<b>Dohsim</b>', openTooltip: true },
    { id: 'ulren_asir', coords: [1098, 5500], icon: icons.city, tooltip: '<b>Ulren Asir</b>', openTooltip: true },
    { id: 'ilreah', coords: [433, 5458], icon: icons.city, tooltip: '<b>Ilreah</b>', openTooltip: true },
    { id: 'montsognir', coords: [1042, 1334], icon: icons.city, tooltip: '<b>Montsognir</b>', openTooltip: true },
    { id: 'rottersvall', coords: [900, 814], icon: icons.city, tooltip: '<b>Rottersvall</b>', openTooltip: true },
    { id: 'hopstad', coords: [1938, 1380], icon: icons.city, tooltip: '<b>Hopstad</b>', openTooltip: true },
    { id: 'skolheim', coords: [1239, 430], icon: icons.city, tooltip: '<b>Skolheim</b>', openTooltip: true },
    { id: 'gokstad', coords: [126, 2096], icon: icons.city, tooltip: '<b>Gokstad</b>', openTooltip: true },
    { id: 'birka', coords: [1220, 2016], icon: icons.city, tooltip: '<b>Birka</b>', openTooltip: true },
    { id: 'nasraah_tej', coords: [4832, 808], icon: icons.city, tooltip: '<b>Nasraah Tej</b>', openTooltip: true },
    { id: 'essadi', coords: [5145, 1139], icon: icons.city, tooltip: '<b>Essadi</b>', openTooltip: true },
    { id: 'altaruk', coords: [4664, 1503], icon: icons.city, tooltip: '<b>Altaruk</b>', openTooltip: true },
    { id: 'meleketi', coords: [5330, 1961], icon: icons.city, tooltip: '<b>Meleketi</b>', openTooltip: true },
    { id: 'medenet', coords: [4573, 2249], icon: icons.city, tooltip: '<b>Medenet</b>', openTooltip: true },
    { id: 'allahed', coords: [3895, 1058], icon: icons.city, tooltip: '<b>Allahed</b>', openTooltip: true }
  ],
  'Forts': [
    { id: 'alsius_door', coords: [1743, 2116], icon: icons.castle, tooltip: '<b>Alsius Door</b>', openTooltip: true },
    { id: 'ignis_door', coords: [4153, 1982], icon: icons.castle, tooltip: '<b>Ignis Door</b>', openTooltip: true },
    { id: 'syrtis_door', coords: [2337, 4065], icon: icons.castle, tooltip: '<b>Syrtis Door</b>', openTooltip: true },
    { id: 'eferias', coords: [3618, 4742], icon: icons.castle, tooltip: '<b>Eferias Castle</b>', openTooltip: true },
    { id: 'herbred', coords: [2844, 3233], icon: icons.fort, tooltip: '<b>Herbred Fort</b>', openTooltip: true },
    { id: 'algaros', coords: [1710, 3212], icon: icons.fort, tooltip: '<b>Algaros Fort</b>', openTooltip: true },
    { id: 'shaanarid', coords: [4611, 3145], icon: icons.castle, tooltip: '<b>Shaanarid Castle</b>', openTooltip: true },
    { id: 'samal', coords: [3699, 2553], icon: icons.fort, tooltip: '<b>Samal Fort</b>', openTooltip: true },
    { id: 'menirah', coords: [3355, 1811], icon: icons.fort, tooltip: '<b>Menirah Fort</b>', openTooltip: true },
    { id: 'imperia', coords: [2786, 1232], icon: icons.castle, tooltip: '<b>Imperia Castle</b>', openTooltip: true },
    { id: 'aggersborg', coords: [2692, 2527], icon: icons.fort, tooltip: '<b>Aggersborg Fort</b>', openTooltip: true },
    { id: 'trelleborg', coords: [1626, 2528], icon: icons.fort, tooltip: '<b>Trelleborg Fort</b>', openTooltip: true }
  ],
  'Interesting': [
    { id: 'sight_ignis_1', coords: [3393, 1687], icon: icons.sight, tooltip: '<b>Camp</b>', openTooltip: true },
    { id: 'sight_island_1', coords: [4295, 6072], icon: icons.sightIsland, tooltip: '<b>Event Island</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_ruins_13', coords: [3182, 5768], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_boat_3', coords: [3138, 5717], icon: icons.sight, tooltip: '<b>Boat</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_ruins_12', coords: [2826, 5078], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_ruins_11', coords: [2960, 4831], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_ruins_10', coords: [2756, 4673], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_ruins_9', coords: [2606, 4389], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_ruins_8', coords: [2737, 5159], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_woodmountain', coords: [2121, 5621], icon: icons.sight, tooltip: '<b>Trees on Mountain</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_ruins_7_graveyard', coords: [2415, 5521], icon: icons.sight, tooltip: '<b>Graveyard</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_ruins_7_graveyard_tomb', coords: [2415, 5521], icon: icons.sight, tooltip: '<b>Graveyard</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_ruins_6_graveyard', coords: [2034, 5547], icon: icons.sight, tooltip: '<b>Graveyard</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_ruins_5', coords: [2041, 5475], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_ruins_2', coords: [2748, 5219], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_ruins_3', coords: [2700, 5248], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_ruins_4', coords: [2704, 5392], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_ruins_1', coords: [2360, 4980], icon: icons.sight, tooltip: '<b>Ruins Island</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_windmill_1', coords: [1364, 5019], icon: icons.sight, tooltip: '<b>Windmill</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_windmill_2', coords: [1340, 4943], icon: icons.sight, tooltip: '<b>Windmill</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_boat_1', coords: [1106, 5093], icon: icons.sight, tooltip: '<b>Boat</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_boat_2', coords: [1207, 4973], icon: icons.sight, tooltip: '<b>Boat</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_mount_goblin', coords: [1464, 4292], icon: icons.sight, tooltip: '<b>Mount Goblin</b>', openTooltip: true },
    { id: 'sight_syrtis_ir_emerald_hills', coords: [1937, 4531], icon: icons.sight, tooltip: '<b>Emerald Hills</b><br>C: 1444,530', openTooltip: true },
    { id: 'sight_ship', coords: [4193, 3767], icon: icons.sight },
    { id: 'sight_alsius_ir_ruins_21', coords: [787, 1949], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ruins_3', coords: [2124, 1935], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ruins_5', coords: [2570, 1891], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ruins_4_camp', coords: [2124, 1935], icon: icons.sight, tooltip: '<b>Camp</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_21_camp', coords: [767, 1912], icon: icons.sight, tooltip: '<b>Camp</b>', openTooltip: true },
    { id: 'sight_alsius_ruins_2', coords: [2231, 1852], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_22', coords: [718, 1880], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ruins_1', coords: [1913, 2350], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_sword_hand', coords: [964, 2029], icon: icons.sight, tooltip: '<b>Sword Hand Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_3', coords: [252, 1885], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_19', coords: [719, 1165], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_20', coords: [1742, 1631], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_13', coords: [770, 1698], icon: icons.sight, tooltip: '<b>Karren</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_18', coords: [556, 1249], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_14', coords: [835, 1639], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_15', coords: [808, 1557], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_16', coords: [499, 1447], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_17', coords: [472, 1389], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_18_camp', coords: [819, 1188], icon: icons.sight, tooltip: '<b>Camp</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_19_camp', coords: [891, 1155], icon: icons.sight, tooltip: '<b>Camp</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_11', coords: [585, 1608], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_4', coords: [203, 1900], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_5', coords: [260, 1805], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_6', coords: [289, 1730], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_7', coords: [347, 1762], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_8', coords: [378, 1699], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_myst_stone', coords: [285, 1676], icon: icons.sight, tooltip: '<b>Mysterios Stone</b>', openTooltip: true },
    { id: 'sight_goblin_homes', coords: [4077, 3725], icon: icons.sight },
    { id: 'sight_ignis_ol_1', coords: [3944, 2902], icon: icons.sight },
    { id: 'sight_alsius_ir_ruins_2', coords: [363, 1876], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_boat_1', coords: [357, 2890], icon: icons.sight, tooltip: '<b>Boat</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_1', coords: [363, 2081], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_boat_2', coords: [280, 2872], icon: icons.sight, tooltip: '<b>Boat</b>', openTooltip: true },
    { id: 'sight_alsius_ir_boat_3', coords: [201, 2831], icon: icons.sight, tooltip: '<b>Boat</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ship_1', coords: [822, 2754], icon: icons.sight, tooltip: '<b>Ship</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ship_2', coords: [755, 2775], icon: icons.sight, tooltip: '<b>Ship</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ship_3', coords: [692, 2777], icon: icons.sight, tooltip: '<b>Ship</b>', openTooltip: true },
    { id: 'sight_ignis_ol_2', coords: [3619, 3285], icon: icons.sight },
    { id: 'sight_stonehenge', coords: [3220, 3754], icon: icons.sight, tooltip: '<b>Stonehenge</b><br><p>Spawn point of super boss Evendim</p><br>C: 3220,3754', openTooltip: true },
    { id: 'sight_syrtis_ol', coords: [2043, 3025], icon: icons.sight, tooltip: '<b>Orc Camp</b><br><p>Spawn point of crafting boss Gobgog</p><br>C: 2043,3025', openTooltip: true },
    { id: 'sight_alsius_ol', coords: [2794, 2189], icon: icons.sight, tooltip: '<b>Orc Camp</b><br><p>Spawn point of crafting boss Gobgog</p><br>C: 2794,2189', openTooltip: true },
    { id: 'sight_syrtis_ir_goblin', coords: [1583, 5886], icon: icons.sight, tooltip: '<b>Goblin Village</b><br>C: 1583,5886', openTooltip: true },
    { id: 'sight_alsius_graveyard', coords: [1970, 2748], icon: icons.sight, tooltip: '<b>Graveyard</b><br>C: 1970,2748', openTooltip: true },
    { id: 'kalmar_ignis_ol', coords: [6019.13, 3667.65], icon: icons.sight, tooltip: '<b>Orc Camp</b>C: 6011,3633', openTooltip: true },
    { id: 'kalmar_alsius_liches', coords: [6034, 3513], icon: icons.sight, tooltip: '<b>Old Liches</b><br><p>Beautiful dark area sorrounded by Old Lichs (probably LV15)</p><br>C: 6034,3513', openTooltip: true },
    { id: 'kalmar_alsius_ship', coords: [5699, 3150], icon: icons.sight, tooltip: '<b>Ship</b><br>C: 5699,3150', openTooltip: true },
    { id: 'sight_alsius_ir_goblor_camp', coords: [1444, 530], icon: icons.sight, tooltip: '<b>Goblor Camp</b><br>C: 1444,530', openTooltip: true },
    { id: 'sight_alsius_ir_fire_tower', coords: [1120, 780], icon: icons.sight, tooltip: '<b>Fire Tower</b><br>C: 1120,780', openTooltip: true },
    { id: 'sight_syrtis_efe_waterfall', coords: [3695, 5098], icon: icons.sight, tooltip: '<b>Water Fall</b><br>C: 3695,5098', openTooltip: true },
    { id: 'sight_ignis_ruins_17', coords: [3779, 1933], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_9', coords: [447, 1653], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_10', coords: [511, 1594], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_sceletton', coords: [3778, 1974], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ruins_1', coords: [3330, 4750], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ruins_2', coords: [2830, 4100], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ruins_3', coords: [1984, 3345], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ruins_4', coords: [2115, 3440], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ruins_4_camp', coords: [2040, 3370], icon: icons.sight, tooltip: '<b>Camp</b>', openTooltip: true },
    { id: 'sight_alsius_ir_mont_fountain', coords: [981, 1335], icon: icons.sight, tooltip: '<b>Fountain</b>', openTooltip: true },
    { id: 'sight_syrtis_ruins_5', coords: [1388, 3294], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ruins_6', coords: [2150, 3090], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ruins_7', coords: [2568, 3061], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ruins_8', coords: [2330, 3000], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ruins_9', coords: [2600, 3310], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ruins_10', coords: [2730, 3491], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ruins_11', coords: [3092, 3532], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ruins_12', coords: [3120, 3373], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_ruins_13', coords: [3427, 3724], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_1', coords: [3592, 3414], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_2', coords: [4067, 3422], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_3', coords: [3057, 3358], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_4', coords: [4036, 3252], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_alsius_ir_ruins_23', coords: [885, 2249], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_14_camp', coords: [4267, 2527], icon: icons.sight, tooltip: '<b>Camp</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_5', coords: [4085, 3224], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_15', coords: [3354, 2957], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_16', coords: [3252, 2761], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_6', coords: [4152, 3091], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_7', coords: [4050, 3080], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_8', coords: [4013, 2973], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_9', coords: [3779, 2751], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_10', coords: [2906, 2649], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_11', coords: [3850, 2608], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_12', coords: [3878, 2582], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_14', coords: [4185, 2641], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_13', coords: [4077, 2572], icon: icons.sight, tooltip: '<b>Ruins</b>', openTooltip: true },
    { id: 'sight_syrtis_alga_waterfall', coords: [1475, 3205], icon: icons.sight, tooltip: '<b>Water Fall</b> (Golden Falls)', openTooltip: true },
    { id: 'sight_ignis_windmill_1', coords: [3506, 2060], icon: icons.sight, tooltip: '<b>Windmill</b>', openTooltip: true },
    { id: 'sight_war_island', coords: [3093, 2915], icon: icons.sight, tooltip: '<b>War Island</b>', openTooltip: true },
    { id: 'sight_ignis_windmill_2', coords: [3460, 2075], icon: icons.sight, tooltip: '<b>Windmill</b>', openTooltip: true },
    { id: 'sight_ignis_ruins_camp', coords: [3517, 2154], icon: icons.sight, tooltip: '<b>Camp</b>', openTooltip: true }
  ],
  'Teleporter': [
    { id: 'telep_imperia', coords: [1672, 2273], icon: icons.teleporter, tooltip: '<b>Teleport to Imperia Castle</b>', openTooltip: true },
    { id: 'telep_eferias', coords: [2536, 4034], icon: icons.teleporter, tooltip: '<b>Teleport to Eferias Castle</b>', openTooltip: true },
    { id: 'telep_bjarr', coords: [247, 1700], icon: icons.teleporter, tooltip: '<b>Teleport to Bjarr</b>', openTooltip: true },
    { id: 'telep_shaanarid', coords: [4031, 1844], icon: icons.teleporter, tooltip: '<b>Teleport to Shaanarid Castle</b>', openTooltip: true },
    { id: 'mael', coords: [1137.41, 5370.37], icon: icons.teleporter, tooltip: '<b>Mael</b> (Teleporter)', openTooltip: true },
    { id: 'lia_rem', coords: [1213.29, 4960.29], icon: icons.teleporter, tooltip: '<b>Lia Rem</b> (Teleporter)', openTooltip: true },
    { id: 'telep_korsum', coords: [2475, 5372], icon: icons.teleporter, tooltip: '<b>Teleport to Korsum</b>', openTooltip: true }
  ],
  'Pendants': [
    { id: 'syrtis_earth_pendant', coords: [2534, 4168], icon: icons.pendants, tooltip: '<b>Earth Pendant Holder</b>', openTooltip: true },
    { id: 'syrtis_earth_altar', coords: [2576, 4198], icon: icons.pendants, tooltip: '<b>Altar of Earth</b>', openTooltip: true },
    { id: 'syrtis_wind_pendant', coords: [1822, 3932], icon: icons.pendants, tooltip: '<b>Wind Pendant Holder</b>', openTooltip: true },
    { id: 'syrtis_wind_altar', coords: [1833, 3881], icon: icons.pendants, tooltip: '<b>Altar of Wind</b>', openTooltip: true },
    { id: 'syrtis_fire_pendant', coords: [2550, 5349], icon: icons.pendants, tooltip: '<b>Fire Pendant Holder</b>', openTooltip: true },
    { id: 'syrtis_fire_altar', coords: [2521, 5334], icon: icons.pendants, tooltip: '<b>Altar of Fire</b>', openTooltip: true },
    { id: 'ignis_water_pendant', coords: [5089, 1751], icon: icons.pendants, tooltip: '<b>Water Pendant Holder</b>', openTooltip: true },
    { id: 'ignis_water_altar', coords: [5072, 1735], icon: icons.pendants, tooltip: '<b>Altar of Water</b>', openTooltip: true },
    { id: 'ignis_wind_pendant', coords: [3892, 1017], icon: icons.pendants, tooltip: '<b>Wind Pendant Holder</b>', openTooltip: true },
    { id: 'ignis_wind_altar', coords: [3925, 1021], icon: icons.pendants, tooltip: '<b>Altar of Wind</b>', openTooltip: true },
    { id: 'ignis_fire_pendant', coords: [4478, 1883], icon: icons.pendants, tooltip: '<b>Fire Pendant Holder</b>', openTooltip: true },
    { id: 'ignis_fire_altar', coords: [4496, 1862], icon: icons.pendants, tooltip: '<b>Altar of Fire</b>', openTooltip: true },
    { id: 'alsius_earth_pendant', coords: [530, 1630], icon: icons.pendants, tooltip: '<b>Earth Pendant Holder</b>', openTooltip: true },
    { id: 'alsius_water_altar', coords: [586, 1209], icon: icons.pendants, tooltip: '<b>Altar of Water</b>', openTooltip: true },
    { id: 'alsius_water_pendant', coords: [620, 1177], icon: icons.pendants, tooltip: '<b>Water Pendant Holder</b>', openTooltip: true },
    { id: 'syrtis_water_altar', coords: [1742, 4670], icon: icons.pendants, tooltip: '<b>Altar of Water</b>', openTooltip: true },
    { id: 'syrtis_water_pendant', coords: [1885, 4788], icon: icons.pendants, tooltip: '<b>Water Pendant Holder</b>', openTooltip: true },
    { id: 'alsius_fire_pendant', coords: [1955, 1692], icon: icons.pendants, tooltip: '<b>Fire Pendant Holder</b>', openTooltip: true },
    { id: 'alsius_fire_altar', coords: [2000, 1666], icon: icons.pendants, tooltip: '<b>Altar of Fire</b>', openTooltip: true },
    { id: 'alsius_earth_alter', coords: [522, 1613], icon: icons.pendants, tooltip: '<b>Altar of Earth</b>', openTooltip: true },
    { id: 'alsius_wind_altar', coords: [853, 2249], icon: icons.pendants, tooltip: '<b>Altar of Wind</b>', openTooltip: true },
    { id: 'alsius_wind_pendant', coords: [812, 2241], icon: icons.pendants, tooltip: '<b>Wind Pendant Holder</b>', openTooltip: true },
    { id: 'alsius_tomb_elements', coords: [969, 1843], icon: icons.pendants, tooltip: '<b>Tomb of the Elements</b>', openTooltip: true }
  ],
  'Altars': [
    { id: 'altar_montsognir', coords: [1080, 1338], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_hopstad', coords: [1863, 1415], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_birka', coords: [1088, 2113], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_3', coords: [1512, 1428], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_aggersborg', coords: [2570, 2220], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_imperia', coords: [2915, 1571], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_trelleborg', coords: [1771, 2632], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_herbred', coords: [2538, 3507], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_algaros', coords: [1789, 3522], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_efe', coords: [2480, 4315], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_dohsim', coords: [2732, 5262], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_raeraia', coords: [2486, 4350], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_korsum', coords: [1707, 3987], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_fisgael', coords: [1054, 4525], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_1', coords: [1875, 5005], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_2', coords: [1941, 4242], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_gokstad', coords: [175, 2221], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_menirah', coords: [3567, 1595], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_samal', coords: [3525, 2234], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_shaanarid', coords: [4191, 3211], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_nasraah_tej', coords: [4824, 776], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_essadi', coords: [5151, 1234], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_allahed', coords: [4098, 1127], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_altaruk', coords: [4798, 1558], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_meleketi', coords: [5341, 1974], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true },
    { id: 'altar_medenet', coords: [4512, 2111], icon: icons.altar, tooltip: '<b>Altar of Rescurection</b>', openTooltip: true }
  ]
});

const overlays = {};
for (const [name, entries] of Object.entries(overlayDefinitions)) {
  overlays[name] = buildLayerGroup(entries);
}

L.control.layers(null, overlays, {
  collapsed: false,
  position: 'topleft'
}).addTo(map);
